# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6bceab4a86ded3990200c01de721f379dca72d58c6fb7659c92def046033ab3b359561ff409de8f78d9c0235adf17d56903cad96892f63045e02c99f7f3b5e9

test:
  secret_key_base: ed71b32524fd4a5adb87b55fcd5474b1efb69d48e2f2a1795291b58156cd25ce2493abe1cc0c31ed2eb75f2a078a8ce93cbcd939e8763bce00daff002a407729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
